export const locale = {
  home: 'Home',
  welcome: 'Welcome',
  products: 'Products',
  reviews: 'Reviews',
  addToCart: 'Add to cart',
  categories: 'Categories',
  register: 'Register',
  login: 'Login',
  logout: 'Logout',
  profile: 'Profile',
  selectCategory: 'Category',
  searchForCategory: 'Search for category',
  selectSort: 'Sort',
  cart: 'Cart',
  total: 'Total',
  order: 'Order',
  checkout: 'Checkout',
  emptyCart: 'Your cart is empty.',
  backToStore: 'Back to store',
  cartProducts: 'Picked products',
  featuredCategories: 'Featured Categories',
  featuredProducts: 'Featured Products',
  showMore: 'Show More',
  price: 'Price',
  error: 'Error',
  loadingError: 'An error occured while loading your data.',
  noData: 'No data',
  noDataForThatQuery: 'We did not find data that you requested.',
  admin: {
    login: 'Admin login'
  }
}
