export const locale = {
  home: 'Home',
  products: 'Products',
  reviews: 'Reviews',
  addToCart: 'Add to cart',
  categories: 'Categories',
  selectCategory: 'Select category',
  searchForCategory: 'Search for category',
  selectSort: 'Select sort type',
  cart: 'Cart',
  total: 'Total',
  order: 'Order',
  checkout: 'Checkout',
  emptyCart: 'Your cart is empty.',
  backToStore: 'Back to store',
  cartProducts: 'Picked products',
  featuredCategories: 'Featured Categories',
  featuredProducts: 'Featured Products',
  showMore: 'Show More',
  price: 'Price',
  error: 'Error',
  loadingError: 'An error occured while loading your data.',
  noData: 'No data',
  noDataForThatQuery: 'We did not find data that you requested.'
}
